/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.h587900.assignment1;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ConverterTest {

    @Test
    void testInchesToMeters() {
        assertEquals(0.0254, Converter.toMeters(1, Converter.Unit.INCHES));
    }

    @Test
    void testFeetToMeters() {
        assertEquals(0.3048, Converter.toMeters(1, Converter.Unit.FEET));
    }

    @Test
    void testMilesToMeters() {
        assertEquals(1609.344, Converter.toMeters(1, Converter.Unit.MILES));
    }

    @Test
    void testMetersToMeters() {
        assertEquals(1, Converter.toMeters(1, Converter.Unit.METERS));
    }

    @Test
    void testInchesFromMeters() {
        assertEquals(1, Converter.fromMeters(0.0254, Converter.Unit.INCHES));
    }

    @Test
    void testFeetFromMeters() {
        assertEquals(1, Converter.fromMeters(0.3048, Converter.Unit.FEET));
    }

    @Test
    void testMilesFromMeters() {
        assertEquals(1, Converter.fromMeters(1609.344, Converter.Unit.MILES));
    }

    @Test
    void testMetersFromMeters() {
        assertEquals(1, Converter.fromMeters(1, Converter.Unit.METERS));
    }

}